services:
  myapp:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: .
          target: usr/src/app
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt
    command: "uvicorn app.main:app --host 0.0.0.0 --reload"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/keyfile.json
    volumes:
      - ../.secrets:/etc/secrets