"""add unique constraint to username + add caption + fix nullables

Revision ID: 607ddd26c8d6
Revises: a75ce16dd7c0
Create Date: 2024-04-12 02:02:19.766236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '607ddd26c8d6'
down_revision: Union[str, None] = 'a75ce16dd7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('profile_picture', sa.String(length=128), nullable=True))
    op.alter_column('auth_user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'auth_user', ['username'])
    op.drop_column('auth_user', 'flag')
    op.add_column('file', sa.Column('caption', sa.Text(), nullable=True))
    op.alter_column('file', 'bucket',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('file', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('file', 'extension',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('file', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('file', 'is_uploaded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('file', 'content_type',
               existing_type=postgresql.ENUM('image', 'video', 'audio', 'document', name='filetype'),
               nullable=False)
    op.alter_column('file', 'source',
               existing_type=postgresql.ENUM('user_upload', 'system_generated', name='filesource'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'source',
               existing_type=postgresql.ENUM('user_upload', 'system_generated', name='filesource'),
               nullable=True)
    op.alter_column('file', 'content_type',
               existing_type=postgresql.ENUM('image', 'video', 'audio', 'document', name='filetype'),
               nullable=True)
    op.alter_column('file', 'is_uploaded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('file', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('file', 'extension',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('file', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('file', 'bucket',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('file', 'caption')
    op.add_column('auth_user', sa.Column('flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.alter_column('auth_user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('auth_user', 'profile_picture')
    # ### end Alembic commands ###
