"""file table added for keeping track of storage blobs

Revision ID: a75ce16dd7c0
Revises: 95ede6f3b233
Create Date: 2024-03-03 18:17:39.544500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75ce16dd7c0'
down_revision: Union[str, None] = '95ede6f3b233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('bucket', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('human_readable_name', sa.String(length=256), nullable=True),
    sa.Column('extension', sa.String(length=16), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('user_email', sa.String(length=256), nullable=True),
    sa.Column('content_type', sa.Enum('image', 'video', 'audio', 'document', name='filetype'), nullable=True),
    sa.Column('source', sa.Enum('user_upload', 'system_generated', name='filesource'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['auth_user.email'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
