name: "Terraform"

on:
  push:
    branches:
      - development
      - staging
      - production

    paths:
      - cloud-infrastructure/dynamic-environments/**

  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: jetrr-vision
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export GCP credentials
        run: echo ${{ secrets.GCP_SA_KEY }} > /tmp/gcp_credentials.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: |
          terraform workspace select ${{ github.ref##*/ }} || terraform workspace new ${{ github.ref##*/ }}
          terraform apply -auto-approve
        working-directory: cloud-infrastructure/dynamic-environments
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
