name: Compile and Upload Static Web Pages

on:
  push:
    branches:
      - development
      - staging
      - production

    paths:
      - web-client/**

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BASE_GCS_PATH: gs://static-web-pages/${{ github.ref_name }}
      GCP_PROJECT_ID: jetrr-vision

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Set this to the Node.js version you need

      - name: Install pnpm  
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: web-client

      - name: Build Astro project
        run: pnpm astro build
        working-directory: web-client

      - name: Upload to GCS using gsutil
        run: |
          gcloud auth list
          gcloud auth application-default login
          echo "Uploading to ${BASE_GCS_PATH}"
          gsutil -m cp -r dist/* $BASE_GCS_PATH
        working-directory: web-client